server:
  port: 8007

# 日志格式
logging:
  pattern:
    console: '%d{HH:mm:ss.SSS} %clr(%-5level) ---  [%-15thread] %cyan(%-50logger{50}):%msg%n'

dubbo:
  application:
    name: shopping_seckill_customer_api
  registry:
    address: zookeeper://192.168.66.199
    port: 2181
    timeout: 10000
  protocol:
    name: dubbo
    port: -1